service: ns-backup

provider:
  name: aws
  runtime: nodejs6.10
  region: ${file(./env.yml):region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "S3BucketBackup" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "S3BucketBackup" }, "/*" ] ]  }

functions:
  backup:
    handler: handler.backup
    timeout: 300
    environment: ${file(./env.yml):lambda}
    events:
      - schedule: rate(1 day)

# you can add CloudFormation resource templates here
resources:
  Resources:
    S3BucketBackup:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(./env.yml):lambda.s3Bucket}
  Outputs:
    S3BucketBackup:
      Description: S3 backup bucket arn
      Value:
         "Fn::GetAtt": [ S3BucketBackup, Arn ]

